<?php $this->alert("Test Alert!", "alert", 1);?>
<?php $this->alert("Test Alert!", "success", 1);?>
<?php $this->alert("Test Alert!", "secondary", 1);?>
<?php $this->alert("Test Alert!", NULL, 1);?>
<?php $this->alert("Test Alert!");?>

<h2>Labels</h2>
<h3>Types</h3>
<code>&lt;?php $this-&gt;label(text, type, style)?&gt;</code><br/><br/>
<?php $this->label("Normal Label")?><br/><br/>
<?php $this->label("Alert Label!", "alert")?><br/><br/>
<?php $this->label("Success Label!", "success")?><br/><br/>
<?php $this->label("Secondary Label!", "secondary")?><br/><br/>
<h3>Styles</h3>
<?php $this->label("Round Label!", NULL, "round")?><br/><br/>
<?php $this->label("Radius Label!", NULL, "radius")?><br/><br/>